import Head from "next/head";
// import Link from "next/link";
import { HeroSection } from "~/components/hero-section";
import { NavigationBar } from "~/components/navigation/navigation-bar";
import { Info } from "~/components/info";
import { SocialProof } from "~/components/social-proof";
import { Faq } from "~/components/faq";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavigationBar />
        <HeroSection />
        <Info />
        <SocialProof />
        <Faq />
      </main>
    </>
  );
}
