import Head from "next/head";
import { HeroSection } from "~/components/hero-section";
import { NavigationBar } from "~/components/navigation/navigation-bar";
import { Info } from "~/components/info";
import { SocialProof } from "~/components/social-proof";
import { Faq } from "~/components/faq";
import { PricingCardBody } from "~/components/pricing-card-body";
import { LinkShortener } from "~/components/shortener";
import { Footer } from "~/components/footer";
import { Final } from "~/components/revolution";
import { Formcomponent } from "~/components/formcomponent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{overflow:"hidden"}}>
        <NavigationBar />
        <HeroSection />
        <Info />
        <SocialProof />
        <PricingCardBody />
        <Formcomponent/>
        <LinkShortener />
        <Faq />
        <Final />
        <Footer />
      </main>
    </>
  );
}
