import Head from "next/head";
import Link from "next/link";
import { HeroSection } from "~/components/hero-section";
import { NavigationBar } from "~/components/navigation/navigation-bar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavigationBar />
        <HeroSection />
      </main>
    </>
  );
}
